#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:2
#SBATCH --job-name=Train-STL10
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=6
#SBATCH --time=00:30:00
#SBATCH --mem=75000M
#SBATCH --output=outputs/train_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/moco-toliz
cp -r $HOME/datasets/stl10_binary $TMPDIR

source activate dino
srun python -u finetune.py --data-dir $TMPDIR